### ISSUE TITLE
Should the README file be updated to load benchmark-init-modes.el?

### ISSUE THREAD

**Issue by jlelong** [dholm/benchmark-init-el#4] opened 2015-01-17 19:03 UTC
In order to make everything work, I had to put 
(let ((benchmark-init.el "/path/to/el-get/benchmark-init/benchmark-init-modes.el"))
  (when (file-exists-p benchmark-init.el)
    (load benchmark-init.el)))
in my .emacs instead of the lines described in the README file.

**Comment by dholm** [comment] 2015-01-17 20:59
@jlelong Hmm, that's a bit odd.  The code in `benchmark-init.el` should be enough to initiate the benchmark during Emacs startup.  `benchmark-init-modes.el` only contains the code used for presenting the results and they contain autoloads so as long as the file is in your `load-path` Emacs should automatically load that file for you whenever you need it.

What error do you get when you load `benchmark-init.el`?

**Comment by jlelong** [comment] 2015-01-18 18:53
I don't get any error when loading `benchmark-init.el`, but the visualization methods are not available until I explicitly load `benchmark-init-modes.el`. I might be doing something wrong?

**Comment by dholm** [comment] 2015-01-22 21:41
@jlelong There are `autoload` cookies for the show-durations-functions.  That means Emacs is supposed to load the file automagically if you try to run one of those functions.  What version of Emacs are you using?

Assuming you are using a fairly recent version of GNU Emacs and the benchmark-init directory is available in the Emacs `load-path` variable this should simply work.

I wanted to maintain the presentation stuff separately from the main file so that it doesn't have any external dependencies since anything loaded before `benchmark-init` itself won't be measured.

**Comment by jlelong** [comment] 2015-01-25 14:21
Thanks for your answer. I use Emacs 24.4 but I have never installed the el-get feature, which I guess is the reason why the functions `(benchmark-init/show-durations-tree, benchmark-init/show-durations-tabulated)` are not loaded automatically.

**Comment by dholm** [comment] 2015-01-26 07:08
@jlelong You don't need `el-get`, the `autoload` feature is built into Emacs.  Did you try adding the `benchmark-init` directory to the Emacs `load-path`?  I think that will solve your problem.

**Comment by jlelong** [comment] 2015-01-27 10:03
Here is the relevant part of my `.emacs`
```
(add-to-list 'load-path "path/to/benchmark-init-el/")
(require 'benchmark-init)
```
If I try to call ``M-x benchmark-init/show-durations-tree``, it answers ``[No Match]``. I have no idea of what I might be doing wrong.

**Comment by dholm** [comment] 2015-03-07 10:45
@jlelong 
Sorry for the long delay in answering.  It looks like I never received an email notification that you posted (or I lost it somehow.)

Your configuration does look correct so I'm a bit confused that it isn't callable from minibuffer.  Just to be sure, you replaced "path/to" with the actual path to where you put benchmark-init-el?

Run `grep -A1 autoload /path/to/benchmark-init-el/*`, it should print something like:

    ../benchmark-init-modes.el:;;;###autoload
    ../benchmark-init-modes.el-(defun benchmark-init/show-durations-tabulated ()
    --
    ../benchmark-init-modes.el:;;;###autoload
    ../benchmark-init-modes.el-(defun benchmark-init/show-durations-tree ()
    --
    ../benchmark-init.el:;;;###autoload
    ../benchmark-init.el-(defun benchmark-init/activate ()

**Comment by dholm** [comment] 2015-03-07 12:19
@jlelong 
I was able to reproduce the issue you were having.  I had misunderstood how the autoloads actually work and I have now pushed a fix for this.  You need to grab the latest version of benchmark-init and run `make` inside it.  Then use the following code in your emacs init script:

    (add-to-list 'load-path "/path/to/benchmark-init/")
    (require 'benchmark-init-loaddefs)
    (benchmark-init/activate)

Replace `/path/to/benchmark-init` with the path to where you installed the package.

**Comment by jlelong** [comment] 2015-03-09 08:40
I confirm that everything works well now.
Thanks for your help and your useful Emacs package.

**Comment by dholm** [comment] 2015-03-14 10:09
Great!  Then I will close this ticket.

**Closed by dholm** 2015-03-14 10:09 UTC
